"""add phone number

Revision ID: 653089576976
Revises: ef36de66ac49
Create Date: 2023-02-08 23:49:08.494734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653089576976'
down_revision = 'ef36de66ac49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
